#ifndef UART_CFG_H
#define UART_CFG_H

#define HMI_BLOCK_UART     UART7_MODULE_NUMBER
#define CONTROL_BLOCK_UART UART7_MODULE_NUMBER
#define RASPBERRY_PI_UART  UART1_MODULE_NUMBER
#define GPS_MODULE_UART UART3_MODULE_NUMBER
#define GSM_MODULE_UART UART3_MODULE_NUMBER

#endif /* UART_CFG_H_ */
