#include "Uart.h"

const Uart_ConfigType Uart_Configuration = {
    /* UART0 Settings */
    UART_OFF, UART_EIGHT_BITS, UART_NO_PARITY, UART_ONE_STOP_BIT, UART_POLLING, 9600,
    
    /* UART1 Settings */
    UART_OFF, UART_EIGHT_BITS, UART_NO_PARITY, UART_ONE_STOP_BIT, UART_POLLING, 9600,
    
    /* UART2 Settings */
    UART_OFF, UART_EIGHT_BITS, UART_NO_PARITY, UART_ONE_STOP_BIT, UART_POLLING, 9600,
    
    /* UART3 Settings */
    UART_OFF, UART_EIGHT_BITS, UART_NO_PARITY, UART_ONE_STOP_BIT, UART_POLLING, 9600,
    
    /* UART4 Settings */
    UART_OFF, UART_EIGHT_BITS, UART_NO_PARITY, UART_ONE_STOP_BIT, UART_POLLING, 9600,
    
    /* UART5 Settings */
    UART_OFF, UART_EIGHT_BITS, UART_NO_PARITY, UART_ONE_STOP_BIT, UART_POLLING, 9600,
    
    /* UART6 Settings */
    UART_OFF, UART_EIGHT_BITS, UART_NO_PARITY, UART_ONE_STOP_BIT, UART_POLLING, 9600,
    
    /* UART7 Settings */
    UART_ON, UART_EIGHT_BITS, UART_NO_PARITY, UART_ONE_STOP_BIT, UART_POLLING, 9600,
};